version: '3'
services:
  postgres:
    image: postgres
    container_name: postgres
    tty: true
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: books
      POSTGRES_USER: samuel
      POSTGRES_PASSWORD: admin