// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"gin-ddd/src/Book/Application"
	"gin-ddd/src/Book/Infrastructure/Persistence"
)

// Injectors from dependency.go:

func InitializeBookFinder() (*Application.BookFinder, error) {
	sqlBookRepository := Persistence.NewSQLBookRepository()
	bookFinder := Application.NewBookFinder(sqlBookRepository)
	return bookFinder, nil
}

func InitializeBookCreator() (*Application.BookCreator, error) {
	sqlBookRepository := Persistence.NewSQLBookRepository()
	bookCreator := Application.NewBookCreator(sqlBookRepository)
	return bookCreator, nil
}
