// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"gin-ddd/src/Book/Application"
	"gin-ddd/src/Book/Infrastructure/Persistence"
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
)

// Injectors from dependency.go:

func InitializeBookFinder() (*Application.BookFinder, error) {
	postgreBookRepository := Persistence.NewSQLBookRepository()
	bookFinder := Application.NewBookFinder(postgreBookRepository)
	return bookFinder, nil
}

// dependency.go:

var context = wire.Struct(&gin.Context{})
