version: '3'
services:
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ..:/var/www/symfony
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
  php:
    container_name: php
    build:
      context: ./php
    ports:
      - '9000:9000'
    volumes:
      - ..:/var/www/symfony

    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    container_name: mysql
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - "../mysql:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: symfony-api-db
      MYSQL_USER: samuel
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql