health_check:
  path: /health-check
  controller: App\Controller\HealthCheckController
  methods: [GET]
get_book:
  path: /book/{id}
  controller: App\Controller\BookController::getByTitle
  methods: [GET]

add_book:
  path: /books/add
  controller: App\Controller\BookController::insert
  methods: [POST]

all_books:
  path: /books
  controller: App\Controller\BookController:all
  methods: [GET]